#include<string>
#include<iostream>

using namespace std;

unsigned int pattern_counter(string genome, string pattern)
{
  const unsigned int k = pattern.size();
  unsigned int count = 0;
  string sub;
  char *p;

  for (unsigned int i = 0; i < genome.length(); ++i) {
    p = &genome[i];

    while (p != &genome[i+k]) {
      sub += *p;
      ++p;
    }

    if (pattern == sub) {
      ++count;
    }
    sub.clear();
  }

  return count;
}

int main()
{
  string genome  = "TACGCGGACGGACAAATACATGGAGGGACAAATCATGGGTGACAAATAGGACAAATGACAAATGGACAAATGACAAATGACAAATAGGAGGACAAATCCTTGGACAAATGAGACAAATTCCGACAAATGACAAATTAGACAAATTGCGACAAATGACAAATTGAATCTATGCGGACAAATATCTAGACAAATTACTGGACAAATGACAAATTCCGACAAATAGGCGGACAAATCGACAAATGACAAATCGCGACAAATGACAAATGACAAATGATTGACAAATAGACAAATACATCTGACAAATCCACCGGAGACAAATACGACAAATCTTGACAAATGACAAATCGGACAAATGTTAGACAAATAACGACAAATTCCACTCTTAAGTGTGCTTCCATGACAAATGACAAATCAGACAAATTACCTGACAAATCGACAAATGCTAGTGACAAATATCGACAAATTGACAAATATTCCCCGACAAATGACAAATCGGACAAATGGCTAGCGGACAAATACCGACAAATGACAAATCAAGACAAATAATGGACAAATGAGGACAAATGGACAAATTCCACCGCGGACAAATGACAAATAGGCGGACAAATGACAAATGACAAATTACGACAAATTTGGACAAATTAAGACAAATGACAAATTGGGCAGACAAATGGACAAATCGTCCAGACAAATTGACAAATTGACAAATCGACAAATACGACAAATGACAAATCTTCGACAAATGACAAATCGACAAATTGGAACTGACAAATAGACAAATTCCTTCGCAAGACAAATGCTGCAGACAAATAGACAAATGACAAATTAAAGACCCGGACAAATGACAAATGACAAATAGGCCCCGACAAATTAGACAAATGACAAATAGACAAATAATGACAAATGACAAATCGCCGACAAATTAAGACAAATTAAGAGGACAAATCAG";
    
 
  unsigned int count = pattern_counter(genome, "GACAAATGA");
  cout << count << endl;
}	
